version: "3.7"

services:
  prometheus:
    image: prom/prometheus:v2.19.0
    container_name: prom
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:7.0.3
    container_name: grafana
    ports:
      - "3000:3000"
